
version: "3.9"
services:
  mongo:
    image: mongo:7
    container_name: aegix-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./backend
    container_name: aegix-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      PORT: 8080
      MONGO_URI: mongodb://mongo:27017/aegixdb
      JWT_SECRET: 05c23e05348bf2ba4102126909dc6e5a3052a94612f99c84e24fd39af08c7dd3
      NODE_ENV: development
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /var/log/nginx:/host-logs/nginx:ro
      - /var/log/suricata:/host-logs/suricata:ro
      - /var/log/fail2ban.log:/host-logs/fail2ban.log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/talhaVM/honeypots/cowrie/logs:/host-logs/cowrie:ro
  frontend:
    build: ./frontend
    container_name: aegix-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
volumes:
  mongo_data:
